import assert from "node:assert/strict";
import test from "node:test";
import { readFile, rm, writeFile } from "fs/promises";
import { join } from "path";
import { getDashboard, organizer, validateEntrants } from "../lib/db";
const file=join("/tmp",`badminton-slots-${process.pid}.json`);process.env.LOCAL_TOURNAMENT_FILE=file;delete process.env.BLOB_READ_WRITE_TOKEN;
async function setup(kind:"singles"|"doubles"="singles"){await rm(file,{force:true});const id=await organizer.createTournament("Open",null);await organizer.importPlayers(id,[{name:"A",elo:1200},{name:"B",elo:1100},{name:"C",elo:1000},{name:"D",elo:900}]);await organizer.addDivision(id,{name:kind==="singles"?"Singles":"Pairs",kind,groupCount:1,playoffSize:0});return {id,d:await getDashboard(id)};}
test("registration calculates slots and creates round-robin fixtures",async()=>{const {id,d}=await setup();const division=d.divisions[0];assert.equal(division.slots.length,0);for(const p of d.players)await organizer.enroll(id,division.id,p.id);const next=await getDashboard(id);assert.equal(next.divisions[0].slots.length,4);assert.equal(next.divisions[0].matches.length,6);assert.equal(next.divisions[0].matches[0].status,"pending");await rm(file,{force:true});});
test("tournament status can move in either direction",async()=>{const {id,d}=await setup(),division=d.divisions[0];await assert.rejects(()=>organizer.lifecycle(id,"active"),/Assign players/);for(const p of d.players)await organizer.enroll(id,division.id,p.id);const slots=(await getDashboard(id)).divisions[0].slots;await organizer.assignSlot(id,division.id,slots[0].id,[d.players[0].id]);await organizer.assignSlot(id,division.id,slots[3].id,[d.players[1].id]);await organizer.lifecycle(id,"active");await organizer.lifecycle(id,"completed");await organizer.lifecycle(id,"scheduled");assert.equal((await getDashboard(id)).event.status,"scheduled");await organizer.lifecycle(id,"active");assert.equal((await getDashboard(id)).event.status,"active");await rm(file,{force:true});});
test("assigned Singles slots activate fixtures and update Elo",async()=>{const {id,d}=await setup(),division=d.divisions[0];for(const p of d.players)await organizer.enroll(id,division.id,p.id);let next=await getDashboard(id),slots=next.divisions[0].slots;await organizer.assignSlot(id,division.id,slots[0].id,[d.players[0].id]);await organizer.assignSlot(id,division.id,slots[3].id,[d.players[1].id]);next=await getDashboard(id);const playable=next.divisions[0].matches.find((m:any)=>m.status==="assigned");assert.ok(playable);await organizer.result(id,playable.id,5,3);next=await getDashboard(id);assert.notEqual(next.players[0].elo,1200);await assert.rejects(()=>organizer.assignSlot(id,division.id,slots[0].id,[d.players[2].id]),/lock/);await rm(file,{force:true});});
test("Doubles slots validate unique registered pair members",async()=>{const {id,d}=await setup("doubles"),division=d.divisions[0];for(const p of d.players)await organizer.enroll(id,division.id,p.id);const slots=(await getDashboard(id)).divisions[0].slots;await organizer.assignSlot(id,division.id,slots[0].id,[d.players[0].id,d.players[1].id]);await assert.rejects(()=>organizer.assignSlot(id,division.id,slots[1].id,[d.players[1].id,d.players[2].id]),/only occupy one slot/);await organizer.assignSlot(id,division.id,slots[1].id,[d.players[2].id,d.players[3].id]);assert.equal((await getDashboard(id)).divisions[0].matches[0].status,"assigned");await rm(file,{force:true});});
test("Doubles distributes pair slots between groups within one slot",async()=>{await rm(file,{force:true});const id=await organizer.createTournament("Pairs",null),rows=Array.from({length:10},(_,i)=>({name:"P"+i,elo:1000}));await organizer.importPlayers(id,rows);await organizer.addDivision(id,{name:"Doubles",kind:"doubles",groupCount:2,playoffSize:0});let d=await getDashboard(id),division=d.divisions[0];for(const p of d.players)await organizer.enroll(id,division.id,p.id);d=await getDashboard(id);const counts=d.divisions[0].slots.reduce((all:Record<string,number>,s:any)=>({...all,[s.group]:(all[s.group]??0)+1}),{});assert.deepEqual(counts,{A:3,B:2});await rm(file,{force:true});});
test("slot capacity is calculated from registrations and group count",async()=>{const {id,d}=await setup(),division=d.divisions[0];for(const p of d.players)await organizer.enroll(id,division.id,p.id);await organizer.assignSlot(id,division.id,(await getDashboard(id)).divisions[0].slots[0].id,[d.players[0].id]);await organizer.updateDivision(id,division.id,{name:"Singles",kind:"singles",groupCount:2,playoffSize:0});const next=await getDashboard(id);assert.equal(next.divisions[0].slotsPerGroup,2);assert.equal(next.divisions[0].slots.length,4);assert.equal(next.divisions[0].entries.length,4);await rm(file,{force:true});});
test("Swiss divisions are removed while legacy round robin is converted to slots",async()=>{const {id}=await setup();const raw=JSON.parse(await readFile(file,"utf8"));raw.version=5;raw.tournaments[0].divisions.push({id:"swiss",name:"Old Swiss",kind:"singles",format:"swiss",groupCount:1,entries:[],teams:[],matches:[],qualifiers:[]});delete raw.tournaments[0].divisions[0].slots;raw.tournaments[0].divisions[0].format="round_robin";raw.tournaments[0].divisions[0].entries=[{playerId:raw.tournaments[0].players[0].id,group:"A"}];await writeFile(file,JSON.stringify(raw));const d=await getDashboard(id);assert.equal(d.divisions.length,1);assert.ok(d.divisions[0].slots.length);await organizer.setup(id,"groups");const rewritten=JSON.parse(await readFile(file,"utf8"));assert.equal(rewritten.version,6);await rm(file,{force:true});});
test("CSV validation flags duplicate and malformed entries",()=>{const rows=validateEntrants([{name:"A",elo:"1000"},{name:"a",elo:"900"},{name:"B",elo:"-1"}]);assert.equal(rows[0].error,"");assert.ok(rows[1].error);assert.ok(rows[2].error);});
