"use client";
import { useState } from "react";
import MatchRail from "@/app/MatchRail";
import { useLocale } from "@/app/LocaleProvider";

export default function EventView({data,organizer=false,onMatch}:{data:any;organizer?:boolean;onMatch?:(match:any)=>void}){
  const {t}=useLocale(),[tab,setTab]=useState("overview"),tabs=[{id:"overview",label:t("overview")},{id:"elo",label:t("eloRanking")},...data.divisions.map((d:any)=>({id:d.id,label:d.name}))];
  const division=data.divisions.find((d:any)=>d.id===tab);
  return <><nav className="division-tabs" aria-label={t("sections")}>{tabs.map((item:any)=><button key={item.id} className={tab===item.id?"active":""} onClick={()=>setTab(item.id)}>{item.label}</button>)}</nav><div className="wide">{tab==="overview"&&<Overview data={data} organizer={organizer} onMatch={onMatch}/>} {tab==="elo"&&<Elo players={data.players}/>} {division&&<Division division={division} organizer={organizer} onMatch={onMatch}/>}</div></>;
}
function Overview({data,organizer,onMatch}:{data:any;organizer:boolean;onMatch?:any}){const {t}=useLocale();return <><MatchRail history={data.history} upcoming={[...data.courts,...data.next,...data.playoffs]} onMatch={organizer?onMatch:undefined}/><section className="grid"><article className="card courts"><p className="eyebrow">{t("liveNow")}</p><h2>{t("courts")}</h2>{data.courts.length?data.courts.map((m:any)=><button className="court" key={m.id} onClick={()=>organizer&&onMatch?.(m)}><small>{t("court")} {m.court_number} · {m.division_name}</small><strong>{m.side_one} <span className="dim">vs</span> {m.side_two}</strong></button>):<p>{t("noCourt")}</p>}</article><article className="card next"><p className="eyebrow">{t("comingUp")}</p><h2>{t("nextMatches")}</h2>{data.next.length?data.next.slice(0,6).map((m:any)=><button className="match" key={m.id} onClick={()=>organizer&&onMatch?.(m)}><span>{m.side_one} vs {m.side_two}</span><small>{m.division_name}</small></button>):<p>{t("noQueue")}</p>}</article></section><MatchesTable title={t("allMatches")} matches={data.all_matches} organizer={organizer} onMatch={onMatch}/></>;}
function Elo({players}:{players:any[]}){const {t}=useLocale(),sorted=[...players].sort((a,b)=>b.elo-a.elo||a.name.localeCompare(b.name));return <section className="grid"><article className="card wide"><p className="eyebrow">{t("ranking")}</p><h2>{t("eloRanking")}</h2><table><thead><tr><th>#</th><th>{t("player")}</th><th>{t("starting")}</th><th>{t("current")}</th><th>{t("change")}</th></tr></thead><tbody>{sorted.map((p:any,index:number)=>{const change=p.elo-p.startingElo;return <tr key={p.id}><td>{index+1}</td><td>{p.name}</td><td>{p.startingElo}</td><td>{p.elo}</td><td className={change>0?"gain":change<0?"loss":""}>{change>0?"+":""}{change}</td></tr>})}</tbody></table></article></section>;}
function Division({division,organizer,onMatch}:{division:any;organizer:boolean;onMatch?:any}){const {t,locale}=useLocale(),groups=[...new Set(division.standings.map((r:any)=>r.group_name??"Standings"))],medals=division.medalists;return <><section className="grid">{medals&&<article className="card wide medal-results"><p className="eyebrow">{locale==="vi"?"Kết quả chung cuộc":"Final results"}</p><h2>{division.name} · {locale==="vi"?"Huy chương":"Medals"}</h2><div className="medal-list"><span><b>🥇 {locale==="vi"?"Vàng":"Gold"}</b>{medals.gold}</span><span><b>🥈 {locale==="vi"?"Bạc":"Silver"}</b>{medals.silver}</span><span><b>🥉 {locale==="vi"?"Đồng":"Bronze"}</b>{medals.bronze}</span></div></article>}<article className="card wide"><p className="eyebrow">{division.kind==="singles"?t("singles"):t("doubles")} · {t("roundRobin")}</p><h2>{division.name}</h2>{groups.map((group:any)=><section className="standings-group" key={group}><h3>{group==="Standings"?t("standings"):`${t("group")} ${group}`}</h3><table className="standings-table"><colgroup><col className="standings-player"/><col/><col/><col/><col className="standings-elo"/></colgroup><thead><tr><th>{t("player")}</th><th>W</th><th>L</th><th>+/-</th><th>{t("currentElo")}</th></tr></thead><tbody>{division.standings.filter((r:any)=>(r.group_name??"Standings")===group).map((r:any)=><tr key={r.id}><td>{r.name}</td><td>{r.wins}</td><td>{r.losses}</td><td>{r.point_difference}</td><td>{r.elo??"—"}</td></tr>)}</tbody></table></section>)}</article></section><MatchesTable title={`${division.name} · ${t("match").toLowerCase()}`} matches={division.matches} organizer={organizer} onMatch={onMatch}/></>;}
function MatchesTable({title,matches,organizer,onMatch}:{title:string;matches:any[];organizer:boolean;onMatch?:any}){const {t}=useLocale(),visible=matches.filter((m:any)=>m.status!=="pending"||m.stage==="playoff");return <section className="grid"><article className="card wide"><h2>{title}</h2><div className="match-table-wrap"><table><thead><tr><th>{t("round")}</th><th>{t("match")}</th><th>{t("score")}</th><th>{t("status")}</th></tr></thead><tbody>{visible.sort((a,b)=>a.order-b.order).map((m:any)=><tr className={organizer&&m.status!=="pending"?"clickable-row":""} key={m.id} onClick={()=>organizer&&m.status!=="pending"&&onMatch?.(m)}><td>{m.stage_label}</td><td className="matchup"><span>{m.side_one}</span><b className="match-versus">VS</b><span>{m.side_two}</span></td><td>{m.score_one??"—"} : {m.score_two??"—"}</td><td>{m.status==="completed"?t("completed"):m.status==="held"?t("held"):m.status==="pending"?t("pending"):m.status==="ready"?t("ready"):t("live")}</td></tr>)}</tbody></table></div></article></section>;}
