"use client";
import { useState } from "react";
import MatchRail from "@/app/MatchRail";

export default function EventView({data,organizer=false,onMatch}:{data:any;organizer?:boolean;onMatch?:(match:any)=>void}){
  const [tab,setTab]=useState("overview"),tabs=[{id:"overview",label:"Overview"},{id:"elo",label:"Elo ranking"},...data.divisions.map((d:any)=>({id:d.id,label:d.name}))];
  const division=data.divisions.find((d:any)=>d.id===tab);
  return <><nav className="division-tabs" aria-label="Tournament sections">{tabs.map((item:any)=><button key={item.id} className={tab===item.id?"active":""} onClick={()=>setTab(item.id)}>{item.label}</button>)}</nav><div className="wide">{tab==="overview"&&<Overview data={data} organizer={organizer} onMatch={onMatch}/>} {tab==="elo"&&<Elo players={data.players}/>} {division&&<Division division={division} organizer={organizer} onMatch={onMatch}/>}</div></>;
}
function Overview({data,organizer,onMatch}:{data:any;organizer:boolean;onMatch?:any}){return <><MatchRail history={data.history} upcoming={[...data.courts,...data.next]}/><section className="grid"><article className="card courts"><p className="eyebrow">Live now</p><h2>Courts</h2>{data.courts.length?data.courts.map((m:any)=><button className="court" key={m.id} onClick={()=>organizer&&onMatch?.(m)}><small>Court {m.court_number} · {m.division_name}</small><strong>{m.side_one} <span className="dim">vs</span> {m.side_two}</strong></button>):<p>No matches are on court.</p>}</article><article className="card next"><p className="eyebrow">Coming up</p><h2>Next matches</h2>{data.next.length?data.next.slice(0,6).map((m:any)=><button className="match" key={m.id} onClick={()=>organizer&&onMatch?.(m)}><span>{m.side_one} vs {m.side_two}</span><small>{m.division_name}</small></button>):<p>No matches are queued.</p>}</article></section><MatchesTable title="All matches" matches={data.all_matches} organizer={organizer} onMatch={onMatch}/></>;}
function Elo({players}:{players:any[]}){const sorted=[...players].sort((a,b)=>b.elo-a.elo||a.name.localeCompare(b.name));return <section className="grid"><article className="card wide"><p className="eyebrow">Tournament ranking</p><h2>Elo ranking</h2><table><thead><tr><th>#</th><th>Player</th><th>Starting</th><th>Current</th><th>Change</th></tr></thead><tbody>{sorted.map((p:any,index:number)=>{const change=p.elo-p.startingElo;return <tr key={p.id}><td>{index+1}</td><td>{p.name}</td><td>{p.startingElo}</td><td>{p.elo}</td><td className={change>0?"gain":change<0?"loss":""}>{change>0?"+":""}{change}</td></tr>})}</tbody></table></article></section>;}
function Division({division,organizer,onMatch}:{division:any;organizer:boolean;onMatch?:any}){const groups=[...new Set(division.standings.map((r:any)=>r.group_name??"Standings"))];return <><section className="grid"><article className="card wide"><p className="eyebrow">{division.kind} · round robin</p><h2>{division.name}</h2>{groups.map((group:any)=><section className="standings-group" key={group}><h3>{group==="Standings"?"Standings":`Group ${group}`}</h3><table className="standings-table"><colgroup><col className="standings-player"/><col/><col/><col/><col className="standings-elo"/></colgroup><thead><tr><th>Player</th><th>W</th><th>L</th><th>+/-</th><th>Current Elo</th></tr></thead><tbody>{division.standings.filter((r:any)=>(r.group_name??"Standings")===group).map((r:any)=><tr key={r.id}><td>{r.name}</td><td>{r.wins}</td><td>{r.losses}</td><td>{r.point_difference}</td><td>{r.elo??"—"}</td></tr>)}</tbody></table></section>)}</article></section><MatchesTable title={division.name+" matches"} matches={division.matches} organizer={organizer} onMatch={onMatch}/></>;}
function MatchesTable({title,matches,organizer,onMatch}:{title:string;matches:any[];organizer:boolean;onMatch?:any}){return <section className="grid"><article className="card wide"><h2>{title}</h2><div className="match-table-wrap"><table><thead><tr><th>Round</th><th>Match</th><th>Score</th><th>Status</th></tr></thead><tbody>{[...matches].sort((a,b)=>a.order-b.order).map((m:any)=><tr className={organizer&&m.status!=="pending"?"clickable-row":""} key={m.id} onClick={()=>organizer&&m.status!=="pending"&&onMatch?.(m)}><td>{m.stage_label}</td><td>{m.side_one} vs {m.side_two}</td><td>{m.score_one??"—"} : {m.score_two??"—"}</td><td>{m.status.replace("_"," ")}</td></tr>)}</tbody></table></div></article></section>;}
